global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8083']
        labels:
          service: 'order-service'
          application: 'e-commerce'
  
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8084']
        labels:
          service: 'payment-service'
          application: 'e-commerce'
  
  - job_name: 'customer-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['customer-service:8081']
        labels:
          service: 'customer-service'
          application: 'e-commerce'
  
  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['inventory-service:8082']
        labels:
          service: 'inventory-service'
          application: 'e-commerce'
  
  - job_name: 'shipping-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['shipping-service:8085']
        labels:
          service: 'shipping-service'
          application: 'e-commerce'
  
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8086']
        labels:
          service: 'notification-service'
          application: 'e-commerce'
  
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8087']
        labels:
          service: 'auth-service'
          application: 'e-commerce'
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']